version: "2.1"
services:
  app:
    image: app:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./env/dev.env
    ports:
      - 4000:4000
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - default

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PSQL_TRUST_LOCALNET: 'true'
      ENCODING: UTF8
    image: postgres:9.6
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - 5432:5432
    networks:
      - default
