version: '3.3'

services:
  grafana:
    image: grafana/grafana:7.1.3
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/.env

volumes:
  grafana_data: {}
